### ISSUE TITLE
[Title] Support links for titles

### ISSUE THREAD

**Issue by vladbailescu** [Adobe-Marketing-Cloud/aem-core-wcm-components#211]
It would be useful if the title would have support for links. The link would be optional and would allow titles to link either to an internal page in AEM, an external URL or an anchor.

**Comment by gabrielwalt** [comment]
(CQ-4221429)

**Comment by gabrielwalt** [comment]
**Acceptance Criteria**

- The IDs must be guaranteed to be unique, otherwise the page might be invalid HTML. To guarantee it to be unique, the hash of the component's path can be used.
- Optionally, the author should be able to set an anchor name to be used for the ID instead of the automatically generated hash.

**Comment by richardhand** [comment]
This enhancement is available in the [2.2.0 release](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.2.0) of the WCM Core Components.
