### ISSUE TITLE
[Page] Support loading configurable JS ClientLib in page head element

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#216]
The clientlib category being maintained in the template (via a content policy) leads to loading the according JS in the body area (compare with https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/903a54005aae0d3cd071bf7715a6ce1852f5f317/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/footer.html#L19 and https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/README.md#loading-of-cssjs). Although this is a good default and makes sense for most of the javascript, there might be some scripts, which necessarily need to be loaded in the head section. Currently that requires overwriting HTL scripts. 

It would be nice if there would be an additional category to maintain on the template level, which is getting loaded in the head section (JS only).

**Comment by gabrielwalt** [comment]
[Page] Support loading configurable JS ClientLib in page head element (CQ-4247319)
As a template author, I want to configure JS that can optionally be loaded in the page head element, instead of the body element, so that I can accommodate scripts that must be loaded upfront, before the page loads.

Acceptance criteria:
In the page policy (design) dialog, allow to define client libraries of which the JS should also be loaded in the page head element (next to the CSS inclusion).
