### ISSUE TITLE
[RTE] Enhance Text/RTE functionality

### ISSUE THREAD

**Issue by brandonmaynard** [Adobe-Marketing-Cloud/aem-core-wcm-components#236]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Enhance the RTE to have more default/optional configurations:
- **Undo/Redo** and **Image** functionality on v2 (optional - on design dialog)
- Add `<hr>` element to **paraformat** on v2 (default - on edit config)
- **Undo/Redo** functionality on v1 (optional - on design dialog)
- Add `<hr>` element to **paraformat** on v1 (default - on edit config)

**Describe the solution you'd like**
Pull Request will be opened with the solution

**Are there alternatives?**
N/A

**Documentation**
Will need to update the following Adobe documentation pages with these enhancements:
- https://www.adobe.com/go/aem_cmp_text_v1
- https://www.adobe.com/go/aem_cmp_text_v2

**Comment by gabrielwalt** [comment]
Thank you for your great contribution, @brandonmaynard!

I like very much the possibility to add the undo/redo and image functionality to the design dialog.
+1 on those!

I'm not sure about adding the HR as paragraph format that is available by default for everybody, because it has some edge cases that the RTE that doesn't seem able to handle properly yet: when having some text selected, the text disappears as it is wrapped inside a `<hr>...</hr>`, and when exiting the RTE, the inner text then reappears as this faulty markup is fixed… Not a big issue, but it's easy enough to add the HR element if needed via the Template Editor, so I'd not make this a default yet.

**Comment by bpauli** [comment]
@gabrielwalt I think we can keep the PR as it is as the Paragraph Styles are not enabled per default.
