### ISSUE TITLE
Embed v1 Clientlibs inside v2 components?

### ISSUE THREAD

**Issue by brandonmaynard** [Adobe-Marketing-Cloud/aem-core-wcm-components#256]
In [List v2](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/list/v2/list), there is no mention of embedding a site clientlib. But in [List v1](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/list/v1/list), the documentation mentions embedding `core.wcm.components.list.v1`. Should v2 also embed this clientlib? If so, I think the documentation needs to be updated.

The same thing in regards to Form Container v2 and Form Container v1.

**Comment by richardhand** [comment]
@brandonmaynard, in the v2 List component we decided to remove the default CSS provided by its site clientlib as it was too opinionated. That's why you don't see it mentioned in the v2 Readme. Styling of lists should be defined as required in a site clientlib.

It is the same case for the v2 Form Container.

I hope that helps, if you have need any more info, just let us know.
