### ISSUE TITLE
Document the URL format for the image component

### ISSUE THREAD

**Issue by raducotescu** [Adobe-Marketing-Cloud/aem-core-wcm-components#28]
The Image Component allows the clients to dynamically request the width of the image, depending on the container width, by relying on a URL format that contains selectors.

This information should be documented so that efficient dispatcher rules can be configured for the component.

**Comment by dixit4patel** [comment]
@kwin    Even I am not getting the smaller rendition image loaded for core image component. 

As you mentioned in #18, It is just confusing that the device emulators shows the CSS pixels and not the real pixels.   However I do have policy configured in "Design" mode since I am using non Editable template, but still the small image is not getting requested. Below is screenshot of my page elements

<img width="951" alt="screen shot 2017-07-10 at 10 54 20 am" src="https://user-images.githubusercontent.com/18273598/28032296-d3387fb8-655e-11e7-99be-cde6dede32ad.png">

**Comment by andyklimczak** [comment]
shouldn't the image component pull the image from the `/content/dam` path instead of from the literal `jcr_content` path? I believe only then you will be able to get the different image renditions

**Comment by justinedelson** [comment]
@andyklimczak not really since the image component can perform non-destructive edits which are specific to an instance of the component.
